sequenceDiagram %% Credential Issuance
    %% participants
    participant JSI as Jane Smith Out of band - Insecure
    participant JSS as Jane Smith Desktop Software - Secure
    participant QDS as QVI Desktop Software - Secure
    participant QOB as QVI Out of band - Insecure
    
    QDS->+QDS: Generate credential from schema
    QDS->-QDS: Sign
    QDS->>JSS: Offer credential to contact

    Alt Accept credential offer
        JSS->+JSS: Verify
        Alt verify success
            JSS->-JSS: Add credential to wallet
        else verify failure
            JSS-XJSI: reject
        end
    else Decline credential offer
        JSS-XJSI: Abandon
    end
