sequenceDiagram %% Credential Issuance
    %% participants
    participant JSI as Jane Smith Out of band - Insecure
    participant JSS as Jane Smith Desktop Software - Secure
    participant EVS as External Verifier Desktop Software - Secure
    participant EVI as External Verifier Out of band - Insecure
    
    EVS->>JSS: Create presentation request for schema type

    Alt Accept
        Alt Has matching credential 
            JSS->>+EVS: Share
            EVS->-EVS: Verify
        else
            JSS-XEVS: No credential
            EVS-XEVI: Abandon
        end
    else Decline
        JSS-XJSI: Abandon
    end
